version: 2.1
jobs:
  playwright:
    docker:
      - image: mcr.microsoft.com/playwright:v1.35.1-jammy
    steps:
      - checkout
      - run:
          name: Set git creds
          command: git config --global user.email "arteezysolo@gmail.com" && git config --global user.name "Vladeezy"
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run tests
          command: npx playwright test
      # Add the following step to generate HTML reports
      - run:
          name: Generate HTML reports
          command: npx playwright test --reporter=dot,json --output=reports
      # Circle CI does not have a built-in GitHub Pages deployment step.
      # However, you can use the "gh-pages" npm package to achieve this.
      # Make sure to update this section according to your project setup.
      - store_test_results:
          path: results.xml
      - store_artifacts:
          path: /tmp/core_dumps
workflows:
  build-and-deploy:
    jobs:
      - playwright